<a href="https://colab.research.google.com/github/Dinesh-Adhithya-H/Deep_Learning_using_Tensorflow/blob/main/Basic_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
x=np.arange(0,10)

In [ ]:
x=tf.constant(x)

In [ ]:
x

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
x=tf.square(x)

In [ ]:
x

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
x=tf.reshape(x,(2,5))

In [ ]:
x

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])>

In [ ]:
y=tf.constant(np.arange(10))

In [ ]:
y=tf.reshape(y,(2,5))

In [ ]:
tf.multiply(x,y)

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]])>

In [ ]:
x*y

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]])>

In [ ]:
tf.constant([1,2,3,4],dtype=tf.float64,shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [ ]:
x+y

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[ 0,  2,  6, 12, 20],
       [30, 42, 56, 72, 90]])>