<a href="https://colab.research.google.com/github/Dinesh-Adhithya-H/Deep_Learning_using_Tensorflow/blob/main/Broadcasting%2C_operator_overloading_and_Numpy_compatibility.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [3]:
x=2
x_sqr=tf.square(x)
print(x_sqr)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
a=tf.constant([[1,2],[3,4]])
tf.add(a,[1,5])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 7],
       [4, 9]], dtype=int32)>

In [9]:
a**2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [10]:
a=tf.constant(3)
b=tf.constant(5)

In [11]:
np.multiply(a,b)

15

In [12]:
nd=np.ones([3,3])

In [14]:
tensor=tf.multiply(nd,3)

In [15]:
tensor.numpy()

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [16]:
v=tf.Variable(0.0)

In [17]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>

In [18]:
v+1

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [19]:
v*5

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [20]:
v.assign_add(5)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=5.0>

In [22]:
v.read_value().numpy()

5.0

In [23]:
class mylayer(tf.keras.layers.Layer):
  def __init__(self):
    super(mylayer,self).__init__()
    self.var1=tf.Variable(100)
    self.var2=[tf.Variable(x) for x in range(2)]

In [24]:
m=mylayer()
[variable.numpy() for variable in m.variables]

[100, 0, 1]

In [31]:
tensor=tf.constant([1,2,3])

In [32]:
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [33]:
tensor=tf.cast(tensor,dtype=tf.float32)

In [34]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>