<a href="https://colab.research.google.com/github/Dinesh-Adhithya-H/Deep_Learning_using_Tensorflow/blob/main/Gradient_Tape_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
x=tf.ones((4,4))
with tf.GradientTape() as t:
  t.watch(x)
  y=tf.reduce_sum(x)
  z=tf.square(y)
dz_dx=t.gradient(z,x)
print(dz_dx)

tf.Tensor(
[[32. 32. 32. 32.]
 [32. 32. 32. 32.]
 [32. 32. 32. 32.]
 [32. 32. 32. 32.]], shape=(4, 4), dtype=float32)


In [8]:
x=tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
  t.watch(x)
  y=x*x
  z=y*y
dz_dx=t.gradient(z,x)
print(dz_dx)

tf.Tensor(108.0, shape=(), dtype=float32)


In [9]:
try:
  dy_dx=t.gradient(y,x)
  print(dy_dx)
except RuntimeError as e:
  print("Error as gradient type can be used only once")

tf.Tensor(6.0, shape=(), dtype=float32)


In [10]:
del t

In [12]:
x=tf.Variable(1.0)
with tf.GradientTape() as t2:
  with tf.GradientTape() as t1:
    y=x*x*x
  dy_dx=t1.gradient(y,x)
d2y_d2x=t2.gradient(dy_dx,x)

In [13]:
dy_dx,d2y_d2x

(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)